import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Start Here',
      items: [{type: 'autogenerated', dirName: 'start-here'}],
    },
    {
      type: 'category',
      label: 'Domain Standards',
      items: [{type: 'autogenerated', dirName: 'domains'}],
    },
    {
      type: 'category',
      label: 'Toolkit and Templates',
      items: [
        {type: 'autogenerated', dirName: 'implementation-toolkit'},
        {type: 'autogenerated', dirName: 'public-sector/templates'},
      ],
    },
    {
      type: 'category',
      label: 'Service Catalog',
      items: [{type: 'autogenerated', dirName: 'service-catalog'}],
    },
    {
      type: 'category',
      label: 'Platform',
      items: [{type: 'autogenerated', dirName: 'platform'}],
    },
    {
      type: 'category',
      label: 'Legal and Policy',
      items: [{type: 'autogenerated', dirName: 'legal-policy'}],
    },
  ],
};

export default sidebars;
